config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show'

  post '/replicate/webhook', to: 'replicate/webhooks#event'
  post '/replicate/webhook/publish', to: 'replicate/webhooks#publish'

  get '/sessions', to: redirect('/sessions/new')

  resource :sessions, only: %i[new create destroy]
  resources :password_resets, only: %i[new create edit update]

  # Public resources
  scope :p do
    get 's/:id', controller: 'public/stories', action: 'show', as: :public_story
  end

  resources :stories, only: %i[new create show update destroy] do
    scope module: :stories do
      resource :covers, only: %i[update]

      resources :chapters, only: %i[create show] do
        scope module: :chapters do
          resource :covers, only: %i[update]
        end

        collection do
          post :publish_next
          post :publish_all
        end

        member do
          post :publish
        end
      end
    end
  end

  resources :nostr_users, except: :show do
    scope module: :nostr_users do
      member do
        resource :refresh_profiles, only: :create

        resource :private_keys, only: [] do
          get :ask_password
          post :reveal
        end
      end

      collection do
        resource :import_profiles, only: %i[new create]
      end
    end
  end

  resources :relays, except: :show do
    scope module: :relays do
      collection do
        resource :resets, only: :create, as: :relays_resets
      end
    end
  end

  resources :thematics, except: :show
  resources :characters, except: :show
  resources :places, except: :show
  resources :prompts, except: :show do
    member do
      post :archive
    end
  end

  resource :settings, only: %i[edit update]
  resolve('Setting') { [:settings] }
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  include Coverable
  include NSFWCoverable

  enum :status, { draft: 0, completed: 1 }, validate: true

  belongs_to :story, counter_cache: true, touch: true

  after_create_commit do
    broadcast_append_to :chapters, target: "chapters_story_#{story.id}"
    generate_cover if completed?
    refresh_previous_chapter if previous?

    broadcast_chapter_details if story.dropper? || (story.complete? && position == 1)
  end

  after_update_commit do
    if status_previously_changed?(from: :draft, to: :completed)
      broadcast_chapter
      generate_cover

      broadcast_chapter_details if story.dropper? || (story.complete? && position == 1)
    elsif published_at_previously_changed?
      broadcast_chapter_details
    end
  end

  scope :published, -> { where.not(published_at: nil) }
  scope :not_published, -> { where(published_at: nil) }
  scope :by_position, -> { order(:position) }

  acts_as_list scope: :story

  def first_to_publish?
    story.chapters.published.blank? && self == story.chapters.first
  end

  def last_to_publish?
    story.chapters.published.count == story.chapters_count &&
      self == last_published
  end

  def last_published
    story.chapters.published.last
  end

  def published?
    !published_at.nil?
  end

  def options
    chat_raw_response_body['options'] || []
  end

  def adventure_ended?
    chat_raw_response_body['adventure_ended'].to_bool
  end

  def broadcast_chapter
    broadcast_replace_to :chapters
  end

  def broadcast_chapter_details
    broadcast_update_to :chapters,
                        locals: { chapter: self },
                        target: :panel_details,
                        partial: 'stories/chapters/details'
  end

  def broadcast_cover
    broadcast_replace_to :chapters,
                         target: "cover_chapter_#{id}",
                         partial: 'stories/chapters/cover'
  end

  def broadcast_cover_placeholder
    broadcast_update_to :chapters,
                        target: "cover_chapter_#{id}",
                        partial: 'stories/chapters/cover_placeholder'
  end

  def most_voted_option
    options[most_voted_option_index]
  end

  def previous
    @previous ||= story.chapters.find_by(position: position - 1)
  end

  def next_one
    @next_one ||= story.chapters.find_by(position: position + 1)
  end

  def previous?
    previous.present?
  end

  def next_one?
    next_one.present?
  end

  private

  def generate_cover
    ReplicateServices::Picture.call(self, summary, publish: publish)
  end

  def refresh_previous_chapter
    broadcast_replace_to :chapters,
                         locals: { chapter: previous },
                         target: "chapter_#{previous.id}"
  end
end

# == Schema Information
#
# Table name: chapters
#
#  id                          :uuid             not null, primary key
#  title                       :string
#  content                     :text
#  summary                     :string
#  published_at                :datetime
#  nostr_identifier            :string
#  replicate_identifier        :string
#  replicate_raw_response_body :json             not null
#  story_id                    :uuid             not null
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  prompt                      :text
#  chat_raw_response_body      :json             not null
#  replicate_raw_request_body  :json             not null
#  position                    :integer          default(1), not null
#  publish                     :boolean          default(FALSE), not null
#  status                      :integer          default("draft"), not null
#  most_voted_option_index     :integer
#
# Indexes
#
#  index_chapters_on_nostr_identifier      (nostr_identifier) UNIQUE
#  index_chapters_on_replicate_identifier  (replicate_identifier) UNIQUE
#  index_chapters_on_story_id              (story_id)
#
# Foreign Keys
#
#  fk_rails_...  (story_id => stories.id)
#

app/controllers/stories/chapters/covers_controller.rb
module Stories
  module Chapters
    class CoversController < ApplicationController
      before_action :set_story
      before_action :set_chapter

      # @route PATCH /stories/:story_id/chapters/:chapter_id/covers (story_chapter_covers)
      # @route PUT /stories/:story_id/chapters/:chapter_id/covers (story_chapter_covers)
      def update
        authorize! @chapter, with: ::Chapters::CoverPolicy

        ReplicateServices::Picture.call(@chapter, @chapter.summary)

        respond_to do |format|
          notice = 'La couverture du chapitre est en cours de création'

          format.html { redirect_to root_path, notice: notice }
          format.turbo_stream { flash.now[:notice] = notice }
        end
      end

      private

      def set_story
        @story = company.stories.find(params[:story_id])
      end

      def set_chapter
        @chapter = @story.chapters.find(params[:chapter_id])
      end
    end
  end
end

app/controllers/stories/chapters_controller.rb
module Stories
  class ChaptersController < ApplicationController
    before_action :set_story
    before_action :set_chapter, only: %i[show publish]

    # @route POST /stories/:story_id/chapters (story_chapters)
    def create
      authorize! Chapter, context: { story: @story }

      @last_chapter = @story.chapters.published.last
      @last_chapter = @story.chapters.last if @last_chapter.blank? && @story.chapters.count == 1

      option_index = params[:option_index]
      index = if option_index.present?
        option_index
      else
        option_count = @last_chapter.options.count
        rand(0..(option_count - 1))
      end

      @last_chapter.update(most_voted_option_index: index.to_i)

      GenerateDropperChapterJob.perform_later(@story, force_publish: true, force_ending: force_end_of_story?)

      respond_to do |format|
        notice = 'Un nouveau chapitre est en cours de création'

        format.html { redirect_to root_path, notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    # @route GET /stories/:story_id/chapters/:id (story_chapter)
    def show
      authorize! @chapter, context: { story: @story }

      @title = "#{@chapter.title} - #{@story.title} | Fabelia"
    end

    # @route POST /stories/:story_id/chapters/publish_next (publish_next_story_chapters)
    def publish_next
      @chapter = @story.chapters.not_published.first

      authorize! @chapter, context: { story: @story }

      NostrJobs::SinglePublisherJob.perform_later(@chapter)

      respond_to do |format|
        notice = 'Le chapitre est en cours de publication sur Nostr'

        format.html { redirect_to root_path, notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    # @route POST /stories/:story_id/chapters/publish_all (publish_all_story_chapters)
    def publish_all
      authorize! Chapter, context: { story: @story }

      NostrJobs::AllPublisherJob.perform_later(@story)

      respond_to do |format|
        notice = 'Tous les chapitres sont en cours de publication sur Nostr'

        format.html { redirect_to root_path, notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    # @route POST /stories/:story_id/chapters/:id/publish (publish_story_chapter)
    def publish
      authorize! @chapter, context: { story: @story }

      NostrJobs::SinglePublisherJob.perform_later(@chapter)

      respond_to do |format|
        notice = 'Le chapitre est en cours de publication sur Nostr'

        format.html { redirect_to root_path, notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    private

    def set_story
      @story = company.stories.find(params[:story_id])
    end

    def set_chapter
      @chapter = @story.chapters.find(params[:id])
    end

    def force_end_of_story?
      params[:force_end].to_bool
    end
  end
end

app/controllers/stories/covers_controller.rb
module Stories
  class CoversController < ApplicationController
    before_action :set_story

    # @route PATCH /stories/:story_id/covers (story_covers)
    # @route PUT /stories/:story_id/covers (story_covers)
    def update
      authorize! @story, with: Stories::CoverPolicy

      ReplicateServices::Picture.call(@story, @story.summary)

      respond_to do |format|
        notice = "La couverture de l'histoire est en cours de création"

        format.html { redirect_to root_path, notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    private

    def set_story
      @story = company.stories.find(params[:story_id])
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: %i[show update destroy]

  # @route GET /stories/new (new_story)
  def new
    authorize! Story

    @story = company.stories.new
  end

  # @route POST /stories (stories)
  def create
    authorize! Story

    @story = company.stories.new(story_params)

    if @story.save
      case mode
      when :dropper
        GenerateDropperStoryJob.perform_later(@story)

        notice = 'Le premier chapitre de cette nouvelle aventure est en cours de création'
      when :complete
        GenerateFullStoryJob.perform_later(@story)

        notice = "L'aventure pré-générée est en cours de création, veuillez patienter le temps que ChatGPT et Replicate finissent de tout générer."
      end

      respond_to do |format|
        format.html { redirect_to root_path, notice: notice }
        format.turbo_stream { flash[:notice] = notice }
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # @route GET /stories/:id (story)
  def show
    authorize! @story

    @title = "#{@story.title} | Fabelia"
  end

  # @route PATCH /stories/:id (story)
  # @route PUT /stories/:id (story)
  def update
    authorize! @story

    @story.toggle!(:enabled)

    respond_to do |format|
      notice = "L'aventure a bien été mise à jour"

      format.html { redirect_to root_path, notice: notice }
      format.turbo_stream { flash.now[:notice] = notice }
    end
  end

  # @route DELETE /stories/:id (story)
  def destroy
    authorize! @story

    NostrJobs::StoryDeletionJob.perform_later(@story)

    respond_to do |format|
      notice = "L'aventure est en cours de suppression"

      format.html { redirect_to root_path, notice: notice }
      format.turbo_stream { flash.now[:notice] = notice }
    end
  end

  private

  def set_story
    @story = company.stories.find(params[:id])
  end

  def story_params
    params.require(:story)
          .permit(
            :mode, :publication_rule, :light_form,
            :nostr_user_id, :thematic_id, :media_prompt_id,
            :narrator_prompt_id, :atmosphere_prompt_id,
            character_ids: [], place_ids: [],
            options: %i[
              minimum_chapters_count maximum_chapters_count
              minimum_poll_sats maximum_poll_sats
              stable_diffusion_prompt
              stable_diffusion_negative_prompt
              publish_previous
              chatgpt_full_story_system_prompt
              chatgpt_dropper_story_system_prompt
              read_as_pdf
            ]
          )
  end

  def mode
    story_params[:mode].to_sym
  end
end

app/views/stories/chapters/_cover.html.slim
figure id=dom_id(chapter, :cover)
  - if chapter.cover.attached?
    = image_tag url_for(chapter.cover), class: 'w-full object-cover rounded-lg h-96'
    figcaption.text-xs.italic.text-center.text-gray-400.px-2.py-1
      = chapter.summary
      |< [#{chapter.story.media_prompt.body}]
  - else
    = render 'stories/chapters/cover_placeholder'

app/views/stories/chapters/_cover_placeholder.html.slim
.flex.items-center.justify-center.w-full.h-96.bg-gray-300.dark:bg-gray-600.rounded.animate-pulse.mb-3
  svg.w-20.h-20.text-gray-200.dark:text-gray-500 aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18"
    path d="M18 0H2a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2Zm-5.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm4.376 10.481A1 1 0 0 1 16 15H4a1 1 0 0 1-.895-1.447l3.5-7A1 1 0 0 1 7.468 6a.965.965 0 0 1 .9.5l2.775 4.757 1.546-1.887a1 1 0 0 1 1.618.1l2.541 4a1 1 0 0 1 .028 1.011Z"

figcaption
  .text-base.leading-relaxed.text-gray-200.dark:text-gray-600.animate-pulse
    div class="h-1.5 bg-gray-200 dark:bg-gray-500/50 rounded-full w-80 mx-auto mb-1"
    div class="h-1.5 bg-gray-200 dark:bg-gray-500/50 rounded-full w-96 mx-auto"

app/views/stories/chapters/_details.html.slim
- story = chapter.story

= turbo_frame_tag :panel_details do
  .panel-details data-controller="modal" data-modal-url-value=Base64.strict_encode64(root_path(story_id: story.id, chapter_id: chapter.id))
    header.mb-3
      .flex.items-center.justify-between.mb-2
        .flex.items-center.gap-2
          - if chapter.draft?
            .h-5.bg-gray-200.dark:bg-gray-500/50.rounded-full.w-72.animate-pulse
          - else
            h3.text-md.md:text-xl.font-semibold
              span.text-gray-400.mr-2
                | [##{chapter.position}]
              = chapter.title

          - if chapter.published?
            .flex.items-center.justify-center.w-6.h-6.p-2.bg-green-500.rounded-full.text-white.text-lg title="Publié le #{l(chapter.published_at)}"
              | ✓

            .flex.items-center.justify-end
              = link_to nostr_client_chapter_url(chapter),
                        class: 'text-gray-500',
                        target: :_blank,
                        title: "Ouvrir l'aventure dans un client Nostr" do
                svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="24" height="24" viewBox="0 0 24 24"
                  path d="M 5 3 C 3.9069372 3 3 3.9069372 3 5 L 3 19 C 3 20.093063 3.9069372 21 5 21 L 19 21 C 20.093063 21 21 20.093063 21 19 L 21 12 L 19 12 L 19 19 L 5 19 L 5 5 L 12 5 L 12 3 L 5 3 z M 14 3 L 14 5 L 17.585938 5 L 8.2929688 14.292969 L 9.7070312 15.707031 L 19 6.4140625 L 19 10 L 21 10 L 21 3 L 14 3 z" fill="currentColor"
          - else
            .flex.items-center.justify-center.w-6.h-6.p-2.bg-orange-500.rounded-full.text-white.text-2xl title="Chapitre non publié"
              | ⨯

        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ml-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" data-action="click->modal#close">
          <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>

      .flex.items-center.justify-between.gap-2.bg-gray-100.rounded-lg.p-2.dark:bg-gray-600
        .flex.items-center.gap-2
          - if story.cover.attached?
            = image_tag polymorphic_path(story.cover.variant(:thumb)), class: 'rounded-lg w-12 h-12'

          div
            = link_to story_path(story), data: { turbo_stream: true } do
              h4.text-sm.text-gray-500.font-semibold= story.title
            .text-xs.text-gray-500.dark:text-gray-400
              = story.human_mode
              |< de <strong>#{story.chapters_count}</strong> chapitres

        - if story.enabled? && !story.ended? && story.dropper? && story.chapters.first.published? && story.chapters.last == chapter && chapter.completed?
          = button_to "Forcer la fin de l'aventure",
                      story_chapters_path(story, force_end: true),
                      method: :post,
                      class: 'w-full bg-orange-500 text-white cursor-pointer px-3 py-2 text-sm w-full hover:bg-orange-400 rounded-lg',
                      data: { turbo_confirm: "Voulez-vous générer et publier le dernier chapitre de cette aventure ?" }

    .space-y-4
      - if chapter.draft?
        = render 'stories/chapters/cover_placeholder'

        .text-base.leading-relaxed.text-gray-200.dark:text-gray-600.animate-pulse.mt-6
          div class="h-2.5 bg-gray-200 dark:bg-gray-500/50 rounded-full w-48 mb-4"
          div class="h-2 bg-gray-200 dark:bg-gray-500/50 rounded-full max-w-[480px] mb-2.5"
          div class="h-2 bg-gray-200 dark:bg-gray-500/50 rounded-full mb-2.5"
          div class="h-2 bg-gray-200 dark:bg-gray-500/50 rounded-full max-w-[440px] mb-2.5"
          div class="h-2 bg-gray-200 dark:bg-gray-500/50 rounded-full max-w-[460px] mb-2.5"
          div class="h-2 bg-gray-200 dark:bg-gray-500/50 rounded-full max-w-[360px]"


      - else
        .relative
          - unless chapter.published?
            = link_to story_chapter_covers_path(story, chapter),
                      class: 'absolute top-0 left-0 rounded-md text-white bg-gray-700/75 p-2 hover:bg-gray-700 transition-colors z-10',
                      title: 'Générer une nouvelle couverture',
                      data: { turbo_method: :patch, turbo_confirm: "Voulez-vous générer une nouvelle couverture pour ce chapitre ?" } do
              svg.transition-all.hover:rotate-180 xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 30 30"
                path d="M 15 3 C 12.031398 3 9.3028202 4.0834384 7.2070312 5.875 A 1.0001 1.0001 0 1 0 8.5058594 7.3945312 C 10.25407 5.9000929 12.516602 5 15 5 C 20.19656 5 24.450989 8.9379267 24.951172 14 L 22 14 L 26 20 L 30 14 L 26.949219 14 C 26.437925 7.8516588 21.277839 3 15 3 z M 4 10 L 0 16 L 3.0507812 16 C 3.562075 22.148341 8.7221607 27 15 27 C 17.968602 27 20.69718 25.916562 22.792969 24.125 A 1.0001 1.0001 0 1 0 21.494141 22.605469 C 19.74593 24.099907 17.483398 25 15 25 C 9.80344 25 5.5490109 21.062074 5.0488281 16 L 8 16 L 4 10 z" fill="currentColor"

          = render 'stories/chapters/cover', chapter: chapter

        .text-base.leading-relaxed.text-gray-500.dark:text-gray-200
          == chapter.content

        - if chapter.options.any?
          .grid.grid-rows-1.gap-3.lg:grid-flow-col-dense
            - if story.complete?
              - if story.disabled?
                - title = "L'aventure est en pause, vous ne pouvez pas publier de chapitre avant de la réactiver"
              - else
                - title = "L'aventure est déjà pré-générée, vous ne pouvez pas faire de choix :)"

              - chapter.options.each do |option, index|
                .w-full.panel-neutral.flex.items-center.justify-center.cursor-not-allowed title=title
                  = option

            - else
              - if chapter.published? && !chapter.last_to_publish?
                - chapter.options.each_with_index do |option, index|
                  .w-full.flex.items-center.justify-center.cursor-not-allowed class=(index == chapter.most_voted_option_index ? 'panel-success' : 'panel-neutral')
                    = option
                    - if index == chapter.most_voted_option_index
                      span.cursor-help.text-xl.ml-1 title="Option  plébiscitée par les utilisateurs" ⚡️

              - elsif story.disabled?
                - chapter.options.each do |option, index|
                  .panel-neutral.cursor-not-allowed title="L'aventure est en pause, vous ne pouvez pas publier de chapitre avant de la réactiver"
                    = option

              - else
                - chapter.options.each_with_index do |option, index|
                  = button_to option,
                              story_chapters_path(story),
                              data: { turbo_confirm: "Voulez-vous forcer la suite de l'aventure avec cette proposition ?" },
                              params: { option_index: index },
                              class: "w-full cursor-pointer #{index == chapter.most_voted_option_index ? 'panel-success' : 'panel-neutral hover:border-secondary-color' }",
                              form: { class: 'w-full' }

        - if chapter.previous? || chapter.next_one?
          .flex.items-center.bg-gray-100.rounded-lg.p-2.dark:bg-gray-600.text-sm class=(chapter.previous? ? 'justify-between' : 'justify-end')
            - if chapter.previous?
              = link_to '< Précédent',
                        story_chapter_path(story, chapter.previous),
                        data: { turbo_stream: true, modal_target: 'prev' },
                        class: 'text-gray-700 dark:text-white hover:text-secondary-color transition-colors'

            - if chapter.next_one?
              = link_to 'Suivant >',
                        story_chapter_path(story, chapter.next_one),
                        data: { turbo_stream: true, modal_target: 'next' },
                        class: 'text-gray-700 dark:text-white hover:text-secondary-color transition-colors'

      - unless chapter.draft?
        / Modal footer
        .pt-4.border-t.border-gray-200.rounded-b.dark:border-gray-600
          - if story.ended?
            p.panel-success.text-center
              | 🎉 Aventure terminée 🎉
          - elsif chapter.completed?
            .grid.grid-rows-1.gap-3.lg:grid-flow-col-dense.lg:auto-cols-max
              - if (story.dropper? && !chapter.published?) || (story.complete? && story.chapters.not_published.first == chapter)
                = button_to 'Publier le chapitre',
                    publish_story_chapter_path(story, chapter),
                    method: :post,
                    class: 'add-link',
                    data: { turbo_confirm: 'Voulez-vous publier ce chapitre ?' },
                    form: { class: 'w-full' }

              - if story.complete?
                = button_to 'Publier tous les chapitres restant',
                            publish_all_story_chapters_path(story),
                            method: :post,
                            class: 'edit-link',
                            data: { turbo_confirm: "Voulez-vous publier tous les chapitres non publiés ?" }

    = render 'turbo_confirm'

app/views/stories/chapters/create.turbo_stream.slim
= render_turbo_stream_flash_messages

app/views/stories/chapters/publish.turbo_stream.slim
= render_turbo_stream_flash_messages

app/views/stories/chapters/publish_all.turbo_stream.slim
= render_turbo_stream_flash_messages

app/views/stories/chapters/publish_next.turbo_stream.slim
= render_turbo_stream_flash_messages

app/views/stories/chapters/show.turbo_stream.slim
= render_turbo_stream_flash_messages

= turbo_stream.replace :panel_details do
  = render 'details', chapter: @chapter

= turbo_stream.set_title @title