config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show'

  post '/replicate/webhook', to: 'replicate/webhooks#event'
  post '/replicate/webhook/publish', to: 'replicate/webhooks#publish'

  get '/sessions', to: redirect('/sessions/new')

  resource :sessions, only: %i[new create destroy]
  resources :password_resets, only: %i[new create edit update]

  # Public resources
  scope :p do
    get 's/:id', controller: 'public/stories', action: 'show', as: :public_story
  end

  resources :stories, only: %i[new create show update destroy] do
    scope module: :stories do
      resource :covers, only: %i[update]

      resources :chapters, only: %i[create show] do
        scope module: :chapters do
          resource :covers, only: %i[update]
        end

        collection do
          post :publish_next
          post :publish_all
        end

        member do
          post :publish
        end
      end
    end
  end

  resources :nostr_users, except: :show do
    scope module: :nostr_users do
      member do
        resource :refresh_profiles, only: :create

        resource :private_keys, only: [] do
          get :ask_password
          post :reveal
        end
      end

      collection do
        resource :import_profiles, only: %i[new create]
      end
    end
  end

  resources :relays, except: :show do
    scope module: :relays do
      collection do
        resource :resets, only: :create, as: :relays_resets
      end
    end
  end

  resources :thematics, except: :show
  resources :characters, except: :show
  resources :places, except: :show
  resources :prompts, except: :show do
    member do
      post :archive
    end
  end

  resource :settings, only: %i[edit update]
  resolve('Setting') { [:settings] }
end

app/models/story.rb
class Story < ApplicationRecord
  include Coverable
  include NSFWCoverable

  enum :mode, { complete: 0, dropper: 1 }, default: :complete, validate: true
  enum :status, { draft: 0, completed: 1 }, default: :draft, validate: true
  enum :publication_rule, {
    do_not_publish: 0,
    publish_first_chapter: 1,
    publish_all_chapters: 2
  }, default: :do_not_publish, validate: true

  attribute :options, StoryOption.to_type

  attr_accessor :light_form

  belongs_to :company
  belongs_to :thematic, counter_cache: true
  belongs_to :nostr_user, counter_cache: true

  with_options inverse_of: :stories do
    belongs_to :media_prompt, -> { where(type: 'MediaPrompt') }, counter_cache: true
    belongs_to :narrator_prompt, -> { where(type: 'NarratorPrompt') }, counter_cache: true
    belongs_to :atmosphere_prompt, -> { where(type: 'AtmospherePrompt') }, counter_cache: true
  end

  has_many :chapters, dependent: :destroy
  has_many :characters_stories, dependent: :delete_all
  has_many :characters, through: :characters_stories
  has_many :places_stories, dependent: :delete_all
  has_many :places, through: :places_stories

  humanize :mode, enum: true
  humanize :publication_rule, enum: true

  before_validation :assign_random_thematic, if: -> { thematic.blank? }
  before_validation :assign_media_prompt, if: :light_form?
  before_validation :assign_narrator_prompt, if: :light_form?
  before_validation :assign_atmosphere_prompt, if: :light_form?

  after_create_commit do
    broadcast_prepend_to :stories

    hide_empty_stories if Story.current?
  end

  after_update_commit do
    if status_previously_changed?(from: :draft, to: :completed)
      broadcast_replace_to :stories
      generate_cover
    end
  end

  after_destroy_commit do
    broadcast_remove_to :stories

    display_empty_stories unless Story.current?
  end

  validates :mode, presence: true, inclusion: { in: modes.keys }
  validates :publication_rule, presence: true, inclusion: { in: publication_rules.keys }
  validates :options, store_model: { merge_errors: true }

  scope :currents, -> { where(adventure_ended_at: nil) }
  scope :ended, -> { where.not(adventure_ended_at: nil) }
  scope :enabled, -> { where(enabled: true) }

  def self.display_placeholder
    Turbo::StreamsChannel.broadcast_update_to(
      %i[stories current],
      target: 'placeholder_story',
      partial: 'stories/placeholder'
    )
  end

  def self.hide_placeholder
    Turbo::StreamsChannel.broadcast_update_to(
      %i[stories current],
      target: 'placeholder_story',
      html: ''
    )
  end

  def self.publishable(language: nil)
    scope = complete.currents.enabled
                    .joins(:chapters)
                    .merge(Chapter.not_published)

    if language.present?
      scope = scope.joins(:nostr_user)
                   .merge(NostrUser.by_language(language))
    end

    scope
  end

  def self.current?
    exists?(adventure_ended_at: nil)
  end

  delegate :human_language, to: :nostr_user

  def current?
    adventure_ended_at.nil? && chapters.published.any?
  end

  def ended?
    adventure_ended_at.present?
  end

  def ended!
    update(adventure_ended_at: Time.current)
  end

  def broadcast_cover
    broadcast_replace_to :stories,
                         target: "cover_story_#{id}",
                         partial: 'stories/cover'
  end

  def broadcast_cover_placeholder
    broadcast_update_to :stories,
                        target: "cover_story_#{id}",
                        partial: 'stories/cover_placeholder'
  end

  def broadcast_next_quick_look_story
    stories = {}
    NostrUser.pluck(:language).each do |language|
      stories[language] = Story.publishable(language: language).first
    end

    broadcast_replace_to :active_stories,
                         partial: 'homes/stories',
                         target: 'quick_look',
                         locals: {
                           stories: stories
                         }
  end

  def broadcast_move_from_current_to_ended
    broadcast_remove_to %i[stories current]
    broadcast_prepend_to %i[stories ended]
  end

  def display_empty_stories
    broadcast_replace_to %i[stories current],
                         target: 'empty_stories',
                         partial: 'homes/empty_stories'
  end

  def hide_empty_stories
    broadcast_replace_to %i[stories current],
                         target: 'empty_stories',
                         html: ''
  end

  def publishable_story?
    Story.publishable(language: nostr_user.language).first == self
  end

  def front_cover_published?
    nostr_identifier.present?
  end

  def back_cover_published?
    back_cover_nostr_identifier.present?
  end

  def language
    nostr_user.language.downcase
  end

  def thematic_name
    language == 'fr' ? thematic.name_fr : thematic.name_en
  end

  def thematic_description
    language == 'fr' ? thematic.description_fr : thematic.description_en
  end

  def publish_me?(index = nil)
    return publish_first_chapter? if dropper?

    publish_all_chapters? || (publish_first_chapter? && index.zero?)
  end

  def disabled?
    !enabled?
  end

  def light_form?
    light_form.to_bool
  end

  private

  def assign_random_thematic
    self.thematic = Thematic.enabled.sample
  end

  def assign_media_prompt
    self.media_prompt = MediaPrompt.enabled.first
  end

  def assign_narrator_prompt
    self.narrator_prompt = NarratorPrompt.enabled.first
  end

  def assign_atmosphere_prompt
    self.atmosphere_prompt = AtmospherePrompt.enabled.first
  end

  def generate_cover
    ReplicateServices::Picture.call(self, summary)
  end
end

# == Schema Information
#
# Table name: stories
#
#  id                          :uuid             not null, primary key
#  title                       :string
#  chapters_count              :integer          default(0), not null
#  adventure_ended_at          :datetime
#  raw_response_body           :json             not null
#  company_id                  :uuid             not null
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  mode                        :integer          default("complete"), not null
#  replicate_identifier        :string
#  replicate_raw_request_body  :json             not null
#  replicate_raw_response_body :json             not null
#  thematic_id                 :uuid
#  enabled                     :boolean          default(TRUE), not null
#  nostr_identifier            :string
#  nostr_user_id               :uuid
#  summary                     :string
#  back_cover_nostr_identifier :string
#  publication_rule            :integer          default("do_not_publish"), not null
#  status                      :integer          default("draft"), not null
#  options                     :jsonb            not null
#  media_prompt_id             :uuid
#  narrator_prompt_id          :uuid
#  atmosphere_prompt_id        :uuid
#
# Indexes
#
#  index_stories_on_atmosphere_prompt_id         (atmosphere_prompt_id)
#  index_stories_on_back_cover_nostr_identifier  (back_cover_nostr_identifier) UNIQUE
#  index_stories_on_company_id                   (company_id)
#  index_stories_on_media_prompt_id              (media_prompt_id)
#  index_stories_on_narrator_prompt_id           (narrator_prompt_id)
#  index_stories_on_nostr_identifier             (nostr_identifier) UNIQUE
#  index_stories_on_nostr_user_id                (nostr_user_id)
#  index_stories_on_replicate_identifier         (replicate_identifier) UNIQUE
#  index_stories_on_thematic_id                  (thematic_id)
#
# Foreign Keys
#
#  fk_rails_...  (atmosphere_prompt_id => prompts.id)
#  fk_rails_...  (company_id => companies.id)
#  fk_rails_...  (media_prompt_id => prompts.id)
#  fk_rails_...  (narrator_prompt_id => prompts.id)
#  fk_rails_...  (nostr_user_id => nostr_users.id)
#  fk_rails_...  (thematic_id => thematics.id)
#

app/controllers/stories/chapters/covers_controller.rb
module Stories
  module Chapters
    class CoversController < ApplicationController
      before_action :set_story
      before_action :set_chapter

      # @route PATCH /stories/:story_id/chapters/:chapter_id/covers (story_chapter_covers)
      # @route PUT /stories/:story_id/chapters/:chapter_id/covers (story_chapter_covers)
      def update
        authorize! @chapter, with: ::Chapters::CoverPolicy

        ReplicateServices::Picture.call(@chapter, @chapter.summary)

        respond_to do |format|
          notice = 'La couverture du chapitre est en cours de création'

          format.html { redirect_to root_path, notice: notice }
          format.turbo_stream { flash.now[:notice] = notice }
        end
      end

      private

      def set_story
        @story = company.stories.find(params[:story_id])
      end

      def set_chapter
        @chapter = @story.chapters.find(params[:chapter_id])
      end
    end
  end
end

app/controllers/stories/chapters_controller.rb
module Stories
  class ChaptersController < ApplicationController
    before_action :set_story
    before_action :set_chapter, only: %i[show publish]

    # @route POST /stories/:story_id/chapters (story_chapters)
    def create
      authorize! Chapter, context: { story: @story }

      @last_chapter = @story.chapters.published.last
      @last_chapter = @story.chapters.last if @last_chapter.blank? && @story.chapters.count == 1

      option_index = params[:option_index]
      index = if option_index.present?
        option_index
      else
        option_count = @last_chapter.options.count
        rand(0..(option_count - 1))
      end

      @last_chapter.update(most_voted_option_index: index.to_i)

      GenerateDropperChapterJob.perform_later(@story, force_publish: true, force_ending: force_end_of_story?)

      respond_to do |format|
        notice = 'Un nouveau chapitre est en cours de création'

        format.html { redirect_to root_path, notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    # @route GET /stories/:story_id/chapters/:id (story_chapter)
    def show
      authorize! @chapter, context: { story: @story }

      @title = "#{@chapter.title} - #{@story.title} | Fabelia"
    end

    # @route POST /stories/:story_id/chapters/publish_next (publish_next_story_chapters)
    def publish_next
      @chapter = @story.chapters.not_published.first

      authorize! @chapter, context: { story: @story }

      NostrJobs::SinglePublisherJob.perform_later(@chapter)

      respond_to do |format|
        notice = 'Le chapitre est en cours de publication sur Nostr'

        format.html { redirect_to root_path, notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    # @route POST /stories/:story_id/chapters/publish_all (publish_all_story_chapters)
    def publish_all
      authorize! Chapter, context: { story: @story }

      NostrJobs::AllPublisherJob.perform_later(@story)

      respond_to do |format|
        notice = 'Tous les chapitres sont en cours de publication sur Nostr'

        format.html { redirect_to root_path, notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    # @route POST /stories/:story_id/chapters/:id/publish (publish_story_chapter)
    def publish
      authorize! @chapter, context: { story: @story }

      NostrJobs::SinglePublisherJob.perform_later(@chapter)

      respond_to do |format|
        notice = 'Le chapitre est en cours de publication sur Nostr'

        format.html { redirect_to root_path, notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    private

    def set_story
      @story = company.stories.find(params[:story_id])
    end

    def set_chapter
      @chapter = @story.chapters.find(params[:id])
    end

    def force_end_of_story?
      params[:force_end].to_bool
    end
  end
end

app/controllers/stories/covers_controller.rb
module Stories
  class CoversController < ApplicationController
    before_action :set_story

    # @route PATCH /stories/:story_id/covers (story_covers)
    # @route PUT /stories/:story_id/covers (story_covers)
    def update
      authorize! @story, with: Stories::CoverPolicy

      ReplicateServices::Picture.call(@story, @story.summary)

      respond_to do |format|
        notice = "La couverture de l'histoire est en cours de création"

        format.html { redirect_to root_path, notice: notice }
        format.turbo_stream { flash.now[:notice] = notice }
      end
    end

    private

    def set_story
      @story = company.stories.find(params[:story_id])
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: %i[show update destroy]

  # @route GET /stories/new (new_story)
  def new
    authorize! Story

    @story = company.stories.new
  end

  # @route POST /stories (stories)
  def create
    authorize! Story

    @story = company.stories.new(story_params)

    if @story.save
      case mode
      when :dropper
        GenerateDropperStoryJob.perform_later(@story)

        notice = 'Le premier chapitre de cette nouvelle aventure est en cours de création'
      when :complete
        GenerateFullStoryJob.perform_later(@story)

        notice = "L'aventure pré-générée est en cours de création, veuillez patienter le temps que ChatGPT et Replicate finissent de tout générer."
      end

      respond_to do |format|
        format.html { redirect_to root_path, notice: notice }
        format.turbo_stream { flash[:notice] = notice }
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # @route GET /stories/:id (story)
  def show
    authorize! @story

    @title = "#{@story.title} | Fabelia"
  end

  # @route PATCH /stories/:id (story)
  # @route PUT /stories/:id (story)
  def update
    authorize! @story

    @story.toggle!(:enabled)

    respond_to do |format|
      notice = "L'aventure a bien été mise à jour"

      format.html { redirect_to root_path, notice: notice }
      format.turbo_stream { flash.now[:notice] = notice }
    end
  end

  # @route DELETE /stories/:id (story)
  def destroy
    authorize! @story

    NostrJobs::StoryDeletionJob.perform_later(@story)

    respond_to do |format|
      notice = "L'aventure est en cours de suppression"

      format.html { redirect_to root_path, notice: notice }
      format.turbo_stream { flash.now[:notice] = notice }
    end
  end

  private

  def set_story
    @story = company.stories.find(params[:id])
  end

  def story_params
    params.require(:story)
          .permit(
            :mode, :publication_rule, :light_form,
            :nostr_user_id, :thematic_id, :media_prompt_id,
            :narrator_prompt_id, :atmosphere_prompt_id,
            character_ids: [], place_ids: [],
            options: %i[
              minimum_chapters_count maximum_chapters_count
              minimum_poll_sats maximum_poll_sats
              stable_diffusion_prompt
              stable_diffusion_negative_prompt
              publish_previous
              chatgpt_full_story_system_prompt
              chatgpt_dropper_story_system_prompt
              read_as_pdf
            ]
          )
  end

  def mode
    story_params[:mode].to_sym
  end
end

app/views/stories/_cover.html.slim
figure id=dom_id(story, :cover)
  - if story.cover.attached?
    = image_tag polymorphic_path(story.cover.variant(:small)), class: 'w-72 rounded-lg mb-3 border-2'
  - else
    = render 'stories/cover_placeholder'

app/views/stories/_cover_placeholder.html.slim
.flex.items-center.justify-center.w-72.h-72.bg-gray-300.dark:bg-gray-700.rounded.animate-pulse.mb-3
  svg.w-10.h-10.text-gray-200.dark:text-gray-600 aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18"
    path d="M18 0H2a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2Zm-5.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm4.376 10.481A1 1 0 0 1 16 15H4a1 1 0 0 1-.895-1.447l3.5-7A1 1 0 0 1 7.468 6a.965.965 0 0 1 .9.5l2.775 4.757 1.546-1.887a1 1 0 0 1 1.618.1l2.541 4a1 1 0 0 1 .028 1.011Z"

app/views/stories/_form_light.html.slim
= simple_form_for Story.new,
                  url: stories_path,
                  html: { \
                    class: 'flex flex-col items-center gap-6 justify-between p-4 bg-gray-200 dark:bg-gray-800 rounded-b-lg', \
                    data: { \
                      controller: 'jumpto', \
                      action: 'turbo:submit-end->jumpto#jump', \
                      jumpto_div_id_value: 'stories' \
                    } \
                  } do |f|

  = f.input :light_form,
            as: :hidden,
            input_html: { value: true },
            wrapper: false

  .flex.flex-col.lg:flex-row.gap-3.justify-between.w-full
    = f.association :thematic,
                    collection: Thematic.enabled,
                    include_blank: '[Aléatoire]',
                    label_html: { class: 'block italic mb-2' },
                    input_html: { \
                      class: 'w-full', \
                      data: { \
                        controller: 'slim-select' \
                      } \
                    }, \
                    wrapper_html: { class: 'text-center w-full' }

    = f.input :mode,
              collection: select_options_for(Story, :modes),
              include_blank: false,
              label_html: { class: 'block italic mb-2' },
              input_html: { \
                class: 'w-full', \
                data: { \
                  controller: 'slim-select', \
                  slim_select_show_search_value: false \
                } \
              }, \
              wrapper_html: { class: 'text-center w-full' }

    = f.association :nostr_user,
                    collection: story_nostr_users_select_options(company),
                    include_blank: false,
                    label_html: { class: 'block italic mb-2' },
                    input_html: { \
                      class: 'w-full', \
                      data: { \
                        controller: 'slim-select' \
                      } \
                    }, \
                    wrapper_html: { class: 'text-center w-full' }

    = f.input :publication_rule,
              collection: select_options_for(Story, :publication_rules),
              include_blank: false,
              label_html: { class: 'block italic mb-2' },
              input_html: { \
                class: 'w-full', \
                data: { \
                  controller: 'slim-select', \
                  slim_select_show_search_value: false \
                } \
              }, \
              wrapper_html: { class: 'text-center w-full' }

  .flex.flex-col.items-center.justify-center.gap-3
    = f.button :submit, 'Créer une aventure rapide',
               class: 'bg-green-600 p-2 rounded-lg text-white cursor-pointer hover:bg-green-500 transition-colors'

    p.dark:text-white
      | ou

      =< link_to 'Créer une aventure sur mesure',
                 new_story_path,
                 class: 'underline'

app/views/stories/_placeholder.html.slim
.border-2.p-3.rounded-lg.space-y-8.animate-pulse.md:space-y-0.md:space-x-8.md:flex.md:items-start.mb-6.dark:bg-transparent.dark:border-gray-600 role="status"
  .w-full.lg:w-2/5.space-y-2
    div class="h-2.5 bg-gray-200 rounded-full w-48 mb-2 mx-auto dark:bg-gray-700"

    .flex.items-center.justify-center.h-72.w-72.bg-gray-300.rounded.mx-auto.dark:bg-gray-700
      svg.w-10.h-10.text-gray-200.dark:text-gray-600 aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18"
        path d="M18 0H2a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2Zm-5.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm4.376 10.481A1 1 0 0 1 16 15H4a1 1 0 0 1-.895-1.447l3.5-7A1 1 0 0 1 7.468 6a.965.965 0 0 1 .9.5l2.775 4.757 1.546-1.887a1 1 0 0 1 1.618.1l2.541 4a1 1 0 0 1 .028 1.011Z"

    div
      div class="h-2 bg-gray-200 rounded-full w-48 mb-1 mx-auto dark:bg-gray-700"
      div class="h-2 bg-gray-200 rounded-full w-52 mx-auto dark:bg-gray-700"

  .w-full.lg:w-3/5.space-y-3
    - 2.times do
      div class="h-4 bg-gray-200 rounded-full w-80 dark:bg-gray-700"
      div class="h-4 bg-gray-200 rounded-full w-96 dark:bg-gray-700"
      div class="h-4 bg-gray-200 rounded-full w-full dark:bg-gray-700"
      div class="h-4 bg-gray-200 rounded-full w-96 dark:bg-gray-700"
      div class="h-4 bg-gray-200 rounded-full w-72 dark:bg-gray-700"
      div class="h-4 bg-gray-200 rounded-full w-full dark:bg-gray-700"

  span.sr-only Chargement...

app/views/stories/_story.html.slim
- if story.draft?
  div id=dom_id(story)
    = render 'stories/placeholder'
- else
  .flex.flex-col.lg:flex-row.justify-between.mb-6 class=('opacity-75' unless story.enabled?) class="lg:max-h-[30rem]" id=dom_id(story)
    .w-full.lg:w-2/5.p-3.flex.flex-col.items-center.text-white.rounded-t-lg.lg:rounded-tr-none.lg:rounded-bl-lg.relative class="px-2.5 #{story.complete? ? 'bg-blue-600 dark:bg-blue-600/50' : 'bg-yellow-600 dark:bg-yellow-600/50' }"
      header.flex.items-center.gap-2.mb-1
        h2.text-lg.font-bold= story.title

        span.text-sm
          - if story.complete?
            =< "(#{story.chapters.published.count}/#{story.chapters_count})"
          - else
            =< "(#{story.chapters.published.count}/X)"

      .flex.items-center.gap-3.mb-3
        p.inline-block.text-xs.font-medium.py-1.rounded class="px-2.5 #{story.complete? ? 'bg-orange-100 text-orange-800' : 'bg-purple-100 text-purple-800' }"
          = story.human_mode

        p.bg-yellow-100.text-yellow-800.text-xs.font-medium.me-2.rounded.dark:bg-gray-700.dark:text-yellow-400.border.border-yellow-400 class="px-2.5 py-0.5"
          = story.human_language

      .relative
        - if !story.ended? && story.enabled? && story.chapters.published.none?
          = link_to story_covers_path(story),
                    class: 'absolute top-1 left-1 rounded-lg text-white bg-gray-700/75 p-2 hover:bg-gray-700 transition-colors z-10',
                    title: 'Générer une nouvelle couverture',
                    data: { turbo_method: :patch, turbo_confirm: "Voulez-vous générer une nouvelle couverture pour cette aventure ?" } do
            svg.transition-all.hover:rotate-180 xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="30" height="30" viewBox="0 0 30 30"
              path d="M 15 3 C 12.031398 3 9.3028202 4.0834384 7.2070312 5.875 A 1.0001 1.0001 0 1 0 8.5058594 7.3945312 C 10.25407 5.9000929 12.516602 5 15 5 C 20.19656 5 24.450989 8.9379267 24.951172 14 L 22 14 L 26 20 L 30 14 L 26.949219 14 C 26.437925 7.8516588 21.277839 3 15 3 z M 4 10 L 0 16 L 3.0507812 16 C 3.562075 22.148341 8.7221607 27 15 27 C 17.968602 27 20.69718 25.916562 22.792969 24.125 A 1.0001 1.0001 0 1 0 21.494141 22.605469 C 19.74593 24.099907 17.483398 25 15 25 C 9.80344 25 5.5490109 21.062074 5.0488281 16 L 8 16 L 4 10 z" fill="currentColor"

        = render 'stories/cover', story: story

        .absolute.-bottom-4.-right-10
          - if story.nostr_user.picture.attached?
            = image_tag url_for(story.nostr_user.picture_url),
                        class: 'w-20 mx-auto mb-1 rounded-full border-2 bg-white',
                        title: story.nostr_user.name
          - else
            .flex.items-center.justify-center.w-20.h-20.text-4xl.text-gray-100.mb-1.rounded-full.border-2.bg-gray-800 title=story.nostr_user.name
              = story.nostr_user.initials

      p.text-sm.italic
        | Créé le
        =< l(story.created_at)
      p.text-sm.italic
        | Mis à jour le
        =< l(story.updated_at)

      = link_to 'Détails', story_path(story),
                class: 'absolute inset-0 indent-[-9999px]',
                id: dom_id(story),
                data: { turbo_stream: true }

    .w-full.lg:w-3/5.bg-gray-50.dark:bg-slate-700/25.rounded-r-lg.lg:overflow-y-auto
      .divide-y.dark:divide-gray-600 id=dom_id(story, :chapters)
        = render story.chapters.with_attached_cover.order(position: :asc)

app/views/stories/new.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-8.gap-3
  h1.text-3xl Création avancée d'une aventure

  .flex.items-center.gap-2
    = link_to '<< Retour', root_path, class: 'back-link'

= render 'form', story: @story

app/views/stories/show.turbo_stream.slim
= render_turbo_stream_flash_messages

= turbo_stream.replace :panel_details do
  = render 'details', story: @story

= turbo_stream.set_title @title

app/views/stories/update.turbo_stream.slim
= render_turbo_stream_flash_messages

- if @story.enabled_previously_changed?
  = turbo_stream.replace dom_id(@story) do
    = render @story

= turbo_stream.replace :panel_details do
  = render 'details', story: @story