config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show'

  post '/replicate/webhook', to: 'replicate/webhooks#event'
  post '/replicate/webhook/publish', to: 'replicate/webhooks#publish'

  get '/sessions', to: redirect('/sessions/new')

  resource :sessions, only: %i[new create destroy]
  resources :password_resets, only: %i[new create edit update]

  # Public resources
  scope :p do
    get 's/:id', controller: 'public/stories', action: 'show', as: :public_story
  end

  resources :stories, only: %i[new create show update destroy] do
    scope module: :stories do
      resource :covers, only: %i[update]

      resources :chapters, only: %i[create show] do
        scope module: :chapters do
          resource :covers, only: %i[update]
        end

        collection do
          post :publish_next
          post :publish_all
        end

        member do
          post :publish
        end
      end
    end
  end

  resources :nostr_users, except: :show do
    scope module: :nostr_users do
      member do
        resource :refresh_profiles, only: :create

        resource :private_keys, only: [] do
          get :ask_password
          post :reveal
        end
      end

      collection do
        resource :import_profiles, only: %i[new create]
      end
    end
  end

  resources :relays, except: :show do
    scope module: :relays do
      collection do
        resource :resets, only: :create, as: :relays_resets
      end
    end
  end

  resources :thematics, except: :show
  resources :characters, except: :show
  resources :places, except: :show
  resources :prompts, except: :show do
    member do
      post :archive
    end
  end

  resource :settings, only: %i[edit update]
  resolve('Setting') { [:settings] }
end

app/models/relay.rb
class Relay < ApplicationRecord
  DEFAULT_LIST = %w[
    wss://no.str.cr
    wss://relay.snort.social
    wss://relay.damus.io
    wss://nostr.bitcoiner.social
    wss://relay.nostr.bg
    wss://nostr.oxtr.dev
    wss://nostr-pub.wellorder.net
    wss://nostr.mom
    wss://nos.lol
  ].freeze

  belongs_to :company
  has_many :nostr_users_relays, dependent: :destroy
  has_many :nostr_users, through: :nostr_users_relays

  acts_as_list scope: :company

  scope :enabled, -> { where(enabled: true) }
  scope :by_position, -> { order(:position) }

  validates :url, presence: true, uniqueness: { case_sensitive: false, scope: :company_id }

  after_validation :clean_url
  after_update :delete_nostr_users_association, if: :marked_as_disabled?

  def self.main
    enabled.by_position.first
  end

  def self.reset!
    transaction do
      Relay.delete_all

      DEFAULT_LIST.each do |relay|
        create!(url: relay)
      end
    end
  end

  # NOTE: title is used as alias to get correct form label association
  def title
    url
  end

  private

  def clean_url
    return if url.blank?

    cleaned_url = url.strip
                     .delete_prefix('http://')
                     .delete_prefix('https://')

    cleaned_url = "wss://#{cleaned_url}" unless cleaned_url.starts_with?('ws://') || cleaned_url.starts_with?('wss://')

    self.url = cleaned_url
  end

  def delete_nostr_users_association
    nostr_users_relays.delete_all
  end

  def marked_as_disabled?
    enabled_previously_changed?(from: true, to: false)
  end
end

# == Schema Information
#
# Table name: relays
#
#  id          :uuid             not null, primary key
#  url         :string
#  description :text
#  enabled     :boolean          default(TRUE), not null
#  company_id  :uuid             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  position    :integer          default(1), not null
#
# Indexes
#
#  index_relays_on_company_id          (company_id)
#  index_relays_on_company_id_and_url  (company_id,url) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (company_id => companies.id)
#

app/controllers/relays/resets_controller.rb
module Relays
  class ResetsController < ApplicationController
    # @route POST /relays/resets (relays_resets)
    def create
      authorize! Relay, with: ResetListPolicy

      company.relays.reset!

      redirect_to relays_path, notice: 'Les relais ont été réinitialisés'
    end
  end
end

app/controllers/relays_controller.rb
class RelaysController < ApplicationController
  before_action :set_relay, only: %i[edit update destroy]

  # @route GET /relays (relays)
  def index
    authorize! Relay

    @relays = company.relays.all.by_position
  end

  # @route GET /relays/new (new_relay)
  def new
    authorize! Relay

    @relay = company.relays.new
  end

  # @route POST /relays (relays)
  def create
    authorize! Relay

    @relay = company.relays.new(relay_params)

    respond_to do |format|
      if @relay.save
        format.html { redirect_to relays_path, notice: 'Relay was successfully created.', status: :see_other }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # @route GET /relays/:id/edit (edit_relay)
  def edit
    authorize! @relay
  end

  # @route PATCH /relays/:id (relay)
  # @route PUT /relays/:id (relay)
  def update
    authorize! @relay

    respond_to do |format|
      if @relay.update(relay_params)
        format.html { redirect_to relays_path, notice: 'Relay was successfully updated.', status: :see_other }
        format.turbo_stream if @relay.position_previously_changed?
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # @route DELETE /relays/:id (relay)
  def destroy
    authorize! @relay

    @relay.destroy

    respond_to do |format|
      notice = 'Relay was successfully destroyed.'

      format.html { redirect_to relays_path, notice: notice }
      format.turbo_stream { flash.now[:notice] = notice }
    end
  end

  private

  def set_relay
    @relay = company.relays.find(params[:id])
  end

  def relay_params
    params.require(:relay).permit(:url, :description, :enabled, :position)
  end
end

app/views/relays/_form.html.slim
= simple_form_for(@relay) do |f|
  .form-inputs
    = f.input :url,
              autofocus: true,
              wrapper_html: { class: 'mb-5' }

    = f.input :description,
              input_html: { class: 'h-48' },
              wrapper_html: { class: 'mb-5' }

    = f.input :enabled,
              wrapper_html: { class: 'mb-5' }

  .form-actions
    = f.button :submit

app/views/relays/_relay.html.slim
- favorite = false

- if relay.first? && relay.enabled?
  - favorite = true
- elsif Relay.main == relay
  - favorite = true

details.row.mb-3 id=dom_id(relay) data-sortable-url=relay_path(relay) class=('opacity-50' unless relay.enabled?)
  summary.flex.items-center.gap-3.justify-between.p-2.relative
    - if favorite
      span.absolute.-top-3.-left-2.cursor-help title="Relay favori" ⭐
    .flex.items-center.gap-3
      span.handle.cursor-move ↕️
      span.font-bold ##{relay.position}

      = relay.url

    .flex.items-center.gap-3
      - if allowed_to?(:update?, relay)
        => link_to 'Modifier', edit_relay_path(relay), class: 'edit-link'

      - if allowed_to?(:destroy?, relay)
        = button_to 'Supprimer', relay,
                    class: 'destroy-button',
                    method: :delete,
                    data: { turbo_confirm: 'Voulez-vous supprimer ce relay ?' }

  .p-2.border-t.dark:border-gray-600
    = relay.description

app/views/relays/destroy.turbo_stream.slim
= render_turbo_stream_flash_messages

app/views/relays/edit.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl Modifier relays

  = link_to '<< Retour', relays_path, class: 'back-link'

= render 'form', relay: @relay

app/views/relays/index.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl Les relais

  - if allowed_to?(:create?, Relay)
    = link_to 'Ajouter un relais', new_relay_path, class: 'add-link'

details.panel-info.mb-6
  summary Relais par défaut

  ul.list-disc.list-inside.mt-1.mb-3
    - Relay::DEFAULT_LIST.each do |relay|
      li= relay

  = button_to 'Réinitialiser les relais',
              relays_resets_path,
              data: { turbo_confirm: 'Voulez-vous réinitialiser les relais ? ⚠️ Vous allez perdre toutes vos configurations actuelles avec vos comptes Nostr ⚠️' },
              class: 'destroy-button'

#relays data-controller="sortable" data-sortable-ghost-class="bg-gray-200" data-sortable-filter-class="opacity-25" data-sortable-model-value="relay"
  = render @relays

app/views/relays/new.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl Ajouter un relay

  = link_to '<< Retour', relays_path, class: 'back-link'

= render 'form', relay: @relay

app/views/relays/update.turbo_stream.slim
- if @relay.position_previously_changed?
  = turbo_stream.update :relays do
    = render Relay.all.by_position