config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#show'

  post '/replicate/webhook', to: 'replicate/webhooks#event'
  post '/replicate/webhook/publish', to: 'replicate/webhooks#publish'

  get '/sessions', to: redirect('/sessions/new')

  resource :sessions, only: %i[new create destroy]
  resources :password_resets, only: %i[new create edit update]

  # Public resources
  scope :p do
    get 's/:id', controller: 'public/stories', action: 'show', as: :public_story
  end

  resources :stories, only: %i[new create show update destroy] do
    scope module: :stories do
      resource :covers, only: %i[update]

      resources :chapters, only: %i[create show] do
        scope module: :chapters do
          resource :covers, only: %i[update]
        end

        collection do
          post :publish_next
          post :publish_all
        end

        member do
          post :publish
        end
      end
    end
  end

  resources :nostr_users, except: :show do
    scope module: :nostr_users do
      member do
        resource :refresh_profiles, only: :create

        resource :private_keys, only: [] do
          get :ask_password
          post :reveal
        end
      end

      collection do
        resource :import_profiles, only: %i[new create]
      end
    end
  end

  resources :relays, except: :show do
    scope module: :relays do
      collection do
        resource :resets, only: :create, as: :relays_resets
      end
    end
  end

  resources :thematics, except: :show
  resources :characters, except: :show
  resources :places, except: :show
  resources :prompts, except: :show do
    member do
      post :archive
    end
  end

  resource :settings, only: %i[edit update]
  resolve('Setting') { [:settings] }
end

app/models/nostr_user.rb
class NostrUser < ApplicationRecord
  include Rails.application.routes.url_helpers

  enum :mode, { generated: 0, imported: 1 }, default: :generated, validate: true

  belongs_to :company
  has_many :nostr_users_relays, dependent: :delete_all
  has_many :relays, -> { by_position }, through: :nostr_users_relays
  has_many :stories, dependent: :destroy

  validates :name, presence: true, if: :generated?
  validates :display_name, presence: true, if: :generated?
  validates :private_key, presence: true
  validates :relays, presence: true
  validates :language, presence: true
  validates :nip05, allow_blank: true, format: { with: User::EMAIL_REGEX }
  validates :lud16, allow_blank: true, format: { with: User::EMAIL_REGEX }

  attribute :metadata_response, NostrProfile.to_type

  has_one_attached :picture
  has_one_attached :banner

  encrypts :private_key

  before_validation :generate_private_key, on: :create, if: :generated?
  before_validation :assign_name, if: -> { name.blank? && display_name.present? }
  before_validation :strip_name, if: -> { name.present? }

  after_destroy_commit do
    broadcast_remove_to :nostr_users
  end

  scope :enabled, -> { where(enabled: true) }
  scope :with_relays, -> { where.associated(:relays) }
  scope :by_language, ->(language) { where(language: language) }

  alias_attribute :profile, :metadata_response

  def public_key
    Nostr.new(private_key: private_key).bech32_keys[:public_key]
  end

  def reduced_public_key
    "#{public_key.first(10)}:#{public_key.last(10)}"
  end

  def human_language
    I18nData.languages(I18n.locale)[language.upcase].capitalize
  rescue StandardError
    'Unknown language'
  end

  def initials
    return if name.blank?

    first, last = name.split

    return first[0].upcase if last.blank?

    "#{first[0]}#{last[0]}".upcase
  end

  def banner_url
    return 'placeholder_nostr_banner.png' unless banner.attached?

    polymorphic_path(banner, only_path: true)
  end

  def picture_url
    return 'placeholder_nostr_picture.png' unless picture.attached?

    polymorphic_path(picture, only_path: true)
  end

  private

  def generate_private_key
    self.private_key ||= SecureRandom.hex(32)
  end

  def assign_name
    self.name = display_name.parameterize(separator: '_')
  end

  def strip_name
    self.name = name.delete('@')
  end
end

# == Schema Information
#
# Table name: nostr_users
#
#  id                :uuid             not null, primary key
#  private_key       :string
#  language          :string(2)        default("EN"), not null
#  company_id        :uuid             not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  stories_count     :integer          default(0), not null
#  enabled           :boolean          default(TRUE), not null
#  metadata_response :json             not null
#  mode              :integer          default("generated"), not null
#  name              :string
#  about             :text
#  nip05             :string
#  website           :string
#  lud16             :string
#  display_name      :string
#
# Indexes
#
#  index_nostr_users_on_company_id   (company_id)
#  index_nostr_users_on_private_key  (private_key) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (company_id => companies.id)
#

app/controllers/nostr_users/import_profiles_controller.rb
module NostrUsers
  class ImportProfilesController < ApplicationController
    # @route GET /nostr_users/import_profiles/new (new_import_profiles)
    def new
      authorize! NostrUser

      @nostr_user = company.nostr_users.new
    end

    # @route POST /nostr_users/import_profiles (import_profiles)
    def create
      authorize! NostrUser

      @nostr_user = company.nostr_users.new(nostr_user_params) do |nostr_user|
        nostr_user.mode = :imported
      end

      if @nostr_user.save
        NostrServices::ImportAccount.call(@nostr_user)

        redirect_to nostr_users_path, notice: 'Nostr user was successfully imported.'
      else
        render :new, status: :unprocessable_entity
      end
    end

    private

    def nostr_user_params
      params.require(:nostr_user)
            .permit(:private_key, :language, :enabled, relay_ids: [])
    end
  end
end

app/controllers/nostr_users/private_keys_controller.rb
module NostrUsers
  class PrivateKeysController < ApplicationController
    before_action :set_nostr_user

    # @route GET /nostr_users/:id/private_keys/ask_password (ask_password_private_keys)
    def ask_password
      authorize! @nostr_user, with: PrivateKeyPolicy
    end

    # @route POST /nostr_users/:id/private_keys/reveal (reveal_private_keys)
    def reveal
      authorize! @nostr_user, with: PrivateKeyPolicy

      if current_user.valid_password?(user_password)
        nostr = Nostr.new(private_key: @nostr_user.private_key)
        @nsec = nostr.bech32_keys[:private_key]
      else
        @nostr_user.errors.add(:user_password, 'Mot de passe invalide')

        render :ask_password, status: :unprocessable_entity
      end
    end

    private

    def nostr_user_params
      params.require(:nostr_user).permit(:user_password)
    end

    def user_password
      nostr_user_params[:user_password]
    end

    def set_nostr_user
      @nostr_user = company.nostr_users.find(params[:id])
    end
  end
end

app/controllers/nostr_users/refresh_profiles_controller.rb
module NostrUsers
  class RefreshProfilesController < ApplicationController
    before_action :set_nostr_user

    # @route POST /nostr_users/:id/refresh_profiles (refresh_profiles)
    def create
      authorize! @nostr_user, with: ProfilePolicy

      NostrServices::ImportProfile.call(@nostr_user)

      redirect_to nostr_users_path, notice: 'Les métadonnées du profil ont bien été rafraîchies'
    rescue URI::InvalidURIError,
           Errno::ECONNREFUSED,
           NostrUserErrors::MissingFavoriteRelay,
           OpenSSL::SSL::SSLError => e
      redirect_to nostr_users_path, alert: e.message
    end

    private

    def set_nostr_user
      @nostr_user = company.nostr_users.find(params[:id])
    end
  end
end

app/controllers/nostr_users_controller.rb
class NostrUsersController < ApplicationController
  before_action :set_nostr_user, only: %i[edit update destroy]

  # @route GET /nostr_users (nostr_users)
  def index
    authorize! NostrUser

    @nostr_users = company.nostr_users.order(id: :asc)
  end

  # @route GET /nostr_users/new (new_nostr_user)
  def new
    authorize! NostrUser

    @nostr_user = company.nostr_users.new(mode: :generated)
  end

  # @route POST /nostr_users (nostr_users)
  def create
    authorize! NostrUser

    @nostr_user = company.nostr_users.new(nostr_user_create_params) do |nostr_user|
      nostr_user.mode = :generated
      nostr_user.relays = [Relay.main]
    end

    if @nostr_user.save
      NostrPublisher::Profile.call_later(@nostr_user)

      redirect_to nostr_users_path, notice: "Votre compte Nostr vient d'être créé ! ⚠️ Assurez-vous d'avoir fait une sauvegarde de votre clé privée pour ne pas perdre votre compte ⚠️"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # @route GET /nostr_users/:id/edit (edit_nostr_user)
  def edit
    authorize! @nostr_user
  end

  # @route PATCH /nostr_users/:id (nostr_user)
  # @route PUT /nostr_users/:id (nostr_user)
  def update
    authorize! @nostr_user

    if @nostr_user.update(nostr_user_update_params)
      NostrPublisher::Profile.call_later(@nostr_user)

      redirect_to nostr_users_path, notice: 'Le compte Nostr a bien été mis à jour.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # @route DELETE /nostr_users/:id (nostr_user)
  def destroy
    authorize! @nostr_user

    @nostr_user.destroy

    respond_to do |format|
      notice = 'Le compte Nostr a bien été supprimé.'

      format.html { redirect_to nostr_users_path, notice: notice }
      format.turbo_stream { flash.now[:notice] = notice }
    end
  end

  private

  def set_nostr_user
    @nostr_user = company.nostr_users.find(params[:id])
  end

  def nostr_user_create_params
    nostr_user_update_params.merge(
      params.require(:nostr_user).permit(:language)
    )
  end

  def nostr_user_update_params
    params.require(:nostr_user)
          .permit(:name, :display_name, :about, :nip05, :lud16,
                  :website, :picture, :banner, :enabled,
                  relay_ids: [])
  end
end

app/views/nostr_users/_form.html.slim
= simple_form_for(nostr_user) do |f|
  .flex.flex-col.items-start.lg:flex-row.justify-between.gap-5
    div
      .flex.justify-between.gap-3.mb-5
        = f.input :display_name,
                  wrapper_html: { class: 'w-full' }

        = f.input :name,
                  wrapper_html: { class: 'w-full' }

        - if f.object.new_record?
          = f.input :language,
                    as: :select,
                    collection: nostr_user_languages_select_options,
                    include_blank: false,
                    input_html: { \
                      class: 'w-full', \
                      data: { \
                        controller: 'slim-select' \
                      } \
                    }, \
                    wrapper_html: { class: 'w-full' }

      = f.input :about,
                input_html: { class: 'h-32' },
                wrapper_html: { class: ' mb-5' }

      .flex.flex-col.lg:flex-row.justify-between.gap-3.mb-8
        = f.input :nip05,
                  as: :email,
                  wrapper_html: { class: 'w-full lg:w-1/3' }

        = f.input :lud16,
                  as: :email,
                  wrapper_html: { class: 'w-full lg:w-1/3' }

        = f.input :website,
                  wrapper_html: { class: 'w-full lg:w-1/3' }

    .flex.flex-col.justify-center.gap-6.mb-5
      div
        = f.input :picture, as: :file

        = image_tag f.object.picture_url, class: 'mx-auto mt-3 w-40 rounded-full'

      div
        = f.input :banner, as: :file

        = image_tag f.object.banner_url, class: 'mx-auto mt-3 w-96'

  = f.association :relays,
                  collection: company.relays.enabled,
                  input_html: { \
                    data: { controller: 'slim-select' }, \
                    class: 'w-full' \
                  },
                  wrapper_html: { class: 'block mb-5' }

  = f.input :enabled,
            as: :boolean,
            wrapper_html: { class: 'mb-5' }

  = f.button :submit

app/views/nostr_users/_nostr_user.html.slim
.row.flex.flex-col.justify-between.shadow-md.hover:shadow-xl.overflow-hidden
  div
    .relative.pb-44.overflow-hidden
      = image_tag nostr_user.banner_url, class: 'absolute inset-0 h-full w-full object-cover transition-transform hover:scale-105'

      span.absolute.bottom-0.left-1.inline-block.mb-2.bg-yellow-100.text-yellow-800.text-xs.font-medium.me-2.rounded.dark:bg-gray-700.dark:text-yellow-400.border.border-yellow-400 class="px-2.5 py-0.5"
        = nostr_user.human_language

    .px-4.py-3
      .flex.items-center.gap-2.mb-3
        = image_tag nostr_user.picture_url, class: 'rounded-full w-16'
        div
          h2.font-bold= nostr_user.display_name
          p.font-medium.text-sm.text-gray-500
            | @
            = nostr_user.name

      .text-sm.mb-3.dark:text-white
        - if nostr_user.about.present?
          == nostr_user.about
        - else
          p.italic.text-sm.text-gray-500.dark:text-white Aucune description

      div
        p.text-sm.text-gray-500.mb-1
          span title="Clé publique" 🔑
          =< link_to nostr_user.reduced_public_key, "#{nostr_client_url}/p/#{nostr_user.public_key}", target: :_blank, class: 'decoration-dashed'

        - if nostr_user.lud16.present?
          p.text-sm.text-gray-500.mb-1
            span title="Adresse Lightning Network" ⚡
            =< nostr_user.lud16

        - if nostr_user.nip05.present?
          p.text-sm.text-gray-500.mb-1
            span title="NIP-05"
              | ☑️
            =< nostr_user.nip05

        - if nostr_user.website.present?
          p.text-sm.text-gray-500.mb-1
            span title="Site internet" 🔗
            =< link_to nostr_user.website, nostr_user.website, target: :_blank

        - if nostr_user.relays.blank?
          p.bg-orange-50.text-orange-500.mt-3.text-sm.p-2 ⚠️ Aucun relais n'est associé à ce compte, vous ne pourrez rien publier avant d'en associer un.
        - else
          details.mt-3.dark:text-white
            summary.cursor-pointer.mb-1 Les relais

            ul.list-disc.list-inside
              - nostr_user.relays.first(3).each_with_index do |relay, index|
                li.panel-success
                  = relay.url
                  - if index.zero?
                    span.cursor-help.ml-1 title="Relay favori" ⭐

  - update_account = allowed_to?(:update?, nostr_user)
  - refresh_profile = allowed_to?(:create?, nostr_user, with: NostrUsers::ProfilePolicy)

  - if update_account || refresh_profile
    footer.border-t.text-xs.text-gray-700.flex.items-center.dark:border-gray-600
      - if refresh_profile
        = button_to 'Rafraîchir les métadonnées',
                    refresh_profiles_path(nostr_user),
                    class: 'inline-block bg-blue-500 text-white w-full p-4 text-center hover:bg-blue-600 transition-colors',
                    title: 'Rafraîchir les métadonnées depuis Nostr',
                    data: { turbo_confirm: 'Voulez-vous rafraîchir les métadonnées depuis Nostr ? ⚠️ Toutes les informations actuelles vont être écrasées' },
                    form: { class: 'w-1/2' }

      - if update_account
        => link_to 'Modifier',
           edit_nostr_user_path(nostr_user),
           class: "inline-block bg-orange-500 p-4 text-center hover:bg-orange-600 transition-colors #{refresh_profile ? 'w-1/2' : 'w-full'}"

app/views/nostr_users/edit.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  .flex.items-center.gap-3
    h1.text-3xl Modifier compte Nostr
    span.bg-yellow-100.text-yellow-800.text-xs.font-medium.me-2.rounded.dark:bg-gray-700.dark:text-yellow-400.border.border-yellow-400 class="px-2.5 py-0.5"
      = @nostr_user.human_language

  = link_to '<< Retour', nostr_users_path, class: 'back-link'

.panel-warning.mb-5
  p Pour éviter des conflits sur les données du compte Nostr, il est recommandé de ne pas faire de modifications sur d'autres clients autres qu'à travers cette interface.
  p En effet, certains clients n'implémentent pas les mêmes métadonnées du profil ce qui peut résulter en l'écrasement de certains champs.

= render 'form', nostr_user: @nostr_user

footer.panel-alert.mt-5
  p.text-xl.mb-3 ⚠️ Zone de danger ⚠️

  .flex.flex-col.lg:flex-row.justify-between.gap-5.mb-2
    - if allowed_to?(:reveal?, @nostr_user, with: NostrUsers::PrivateKeyPolicy)
      .w-full.lg:w-2/3
        p.font-bold.text-lg.underline.mb-1 Sauvegarde des clés et conseils de sécurité
        p Votre compte est sécurisé par une clé secrète. La clé est une longue chaîne aléatoire commençant par <strong>nsec1</strong>. Toute personne ayant accès à votre clé secrète peut publier du contenu en utilisant votre identité.

        ul.list-disc.list-inside.mb-3
          li Ne communiquez <strong>jamais</strong> votre clé secrète à un site Web ou un logiciel auquel vous ne faites pas confiance.
          li Les développeurs de Fabelia ne vous demanderont <strong>jamais</strong> votre clé secrète.
          li
            <strong>Conservez</strong> une sauvegarde sécurisée de votre clé secrète pour la récupération de compte. Nous vous recommandons d'utiliser un gestionnaire de mots de passe et/ou de noter sur une feuille de papier.

        = turbo_frame_tag dom_id(@nostr_user, :private_key) do
          = link_to 'Révéler la clé secrète 🔑',
                    ask_password_private_keys_path(@nostr_user),
                    class: 'inline-block bg-red-600 text-white p-2 rounded-lg'

    - if allowed_to?(:destroy?, @nostr_user)
      .w-full.lg:w-1/3
        p.font-bold.text-lg.underline.mb-1 Supprimer le compte Nostr

        p En supprimant ce compte Nostr sur Fabelia, vous ne serez plus en mesure de publier sur Nostr. Si vous avez fait une sauvegarde de votre clé secrète, vous pourrez toujours réimporter les données depuis les relais Nostr.
        p.mb-2 Toutes vos publications restent présentes sur les relais configurés.

        = button_to 'Supprimer', @nostr_user,
                    class: 'inline-block bg-red-600 text-white p-2 rounded-lg cursor-pointer',
                    method: :delete,
                    form: { class: 'text-right' },
                    data: { turbo_confirm: 'Voulez-vous supprimer ce compte Nostr ? ⚠️ cette action est irréversible et vous ne pourrez plus faire de publication sur ce compte ⚠️' }

app/views/nostr_users/index.html.slim
= turbo_stream_from :nostr_users

header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  .flex.items-end.gap-3
    h1.text-3xl Comptes Nostr

  - if allowed_to?(:create?, NostrUser)
    .flex.items-center.gap-3
      = link_to 'Créer un compte Nostr', new_nostr_user_path, class: 'add-link'

      = link_to 'Importer un compte Nostr', new_import_profiles_path, class: 'blue-button'

- if Relay.none?
  p.bg-red-200.border.border-red-600.p-2.rounded-lg
    | Vous devez
    =<> link_to 'configurer', new_relay_path, class: 'underline'
    | au moins un relay pour gérer un compte Nostr

- elsif Relay.any? && Relay.enabled.none?
  p.bg-red-200.border.border-red-600.p-2.rounded-lg
    | Vous devez
    =<> link_to 'activer', relays_path, class: 'underline'
    | au moins un relay pour gérer un compte Nostr

- else
  #nostr_users.grid.grid-cols-1.md:grid-cols-2.lg:grid-cols-3.gap-3
    = render @nostr_users

app/views/nostr_users/new.html.slim
header.flex.flex-col.lg:flex-row.items-center.justify-between.mb-6.gap-3
  h1.text-3xl Ajouter un compte Nostr

  = link_to '<< Retour', nostr_users_path, class: 'back-link'

= render 'form', nostr_user: @nostr_user